title: Your awesome title
email: your-email@example.com
description: >- # this means to ignore newlines until "baseurl:"
  Write an awesome description for your new site here. You can edit this
  line in _config.yml. It will appear in your document head meta (for
  Google search results) and in your feed.xml site description.
baseurl: "dolimpan.github.io" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com
twitter_username: jekyllrb
github_username:  jekyll



pagination:
  enabled: true
  per_page: 7
  permalink: "/dev/prev/web/page/:num/" # 페이지네이션 경로 설정
  title: ":title - page :num"
  sort_field: "date"
  sort_reverse: true

# Build settings
theme: minima
plugins:
  - jekyll-feed
  - jekyll-paginate-v2
